### ISSUE TITLE
在ArchLinux下无法正常运行

### ISSUE THREAD

**Issue by zxp19821005** [gozaoo/BlurLyric2.0#30]
我个人根据打包的deb文件做了移植，地址为：[https://aur.archlinux.org/packages/blurlyric-bin](https://aur.archlinux.org/packages/blurlyric-bin)。
安装后运行报错，内容如下：
```
$ /opt/blurlyric/blurlyric 
failed to load config from /opt/blurlyric/resources/app/vite.config.js
(node:100076) UnhandledPromiseRejectionWarning: Error: Cannot find module '@vitejs/plugin-vue'
Require stack:
- /opt/blurlyric/resources/app/vite.config.js
- /opt/blurlyric/resources/app/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js
- /opt/blurlyric/resources/app/node_modules/vite/dist/node/index.js
- /opt/blurlyric/resources/app/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1054:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109872)
    at Module._load (node:internal/modules/cjs/loader:900:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/blurlyric/resources/app/vite.config.js:30:33)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at require.extensions.<computed> [as .js] (/opt/blurlyric/resources/app/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61973:20)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
(Use `blurlyric --trace-warnings ...` to show where the warning was created)
(node:100076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:100076) electron: Failed to load URL: http://localhost:18775/ with error: ERR_CONNECTION_REFUSED
Error: ENOENT: no such file or directory, open './util/config.json'
    at Object.openSync (node:fs:600:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.writeFileSync (node:fs:2221:35)
    at generateConfig (/opt/blurlyric/resources/app/generateConfig.js:14:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.start (/opt/blurlyric/resources/app/app.js:5:3) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './util/config.json'
}
server running @ http://localhost:18775
```

**Comment by zxp19821005** [comment]
按照README.md中的内容，下载源代码编译后结果相同。

**Comment by g2nnyS** [comment]
看起来缺少了`@vitejs/plugin-vue`模块，并且无法找到`'./util/config.json'`路径，我看看啥原因导致的

**Comment by gozaoo** [comment]
请问，是否能够访问且有响应？ http://localhost:18775

**Comment by gozaoo** [comment]
已将@vitejs/plugin-vue组件加入常规依赖组件，理论上已修复，请更新源码后重新构建
构建方法：
`
npm install 
npm build
npm run make
`
后输出到 `./out/make/(系统号)/`
中

**Comment by zxp19821005** [comment]
额，不管是在Release页面还是在项目主页  都没有看到最近的提交或者发布啊

**Comment by zxp19821005** [comment]
额，不管是在Release页面还是在项目主页  都没有看到最近的提交或者发布啊

**Comment by gozaoo** [comment]
是这样的，请在dev分支下载，我们将在今日将dev与main分支合并~

**Comment by gozaoo** [comment]
![image](https://github.com/Project-And-Factory/BlurLyric/assets/81862662/97b8e96c-6452-4650-a4fa-c04d30208c95)

**Comment by zxp19821005** [comment]
好的，不好意思，是我没注意。谢谢！
